# Generated by Django 3.1.14 on 2023-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('employee', 'Employee'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
